"
A language is considered to be nearly extinct when it is spoken by only a few elderly native speakers.

The phrase ""Nearly extinct"" is used to indicate those languages of fewer than 50 speakers and other languages for which the number of speakers is a very small fraction of the ethnic group.

"
Class {
	#name : #ENearlyExtinctLanguage,
	#superclass : #ELanguageStatus,
	#category : #'Ethnologue-Language'
}

{ #category : #accessing }
ENearlyExtinctLanguage class >> identifier [
	" Answer the receiver's ethnologue code table identifier "

	^ $N
]
